"""rename customer to account, add asset + renewal loop

Revision ID: 0c29e674c81a
Revises: 2d3ac137aa03
Create Date: 2026-08-18 00:00:00.000000

Hand-written, not autogenerated: `alembic revision --autogenerate` has no
concept of "rename" — it would see the old `customer`/`customer_type`/
`customer_assignment` tables and every `customer_id` column disappear from
the models and emit DROP + CREATE pairs, discarding data and constraint
history for no reason. Every rename below uses op.rename_table() /
alter_column(new_column_name=...) instead, which Postgres handles as an
in-place catalog update — existing rows and foreign keys survive untouched
(a FK tracks the referenced table by OID, not by name, so renaming the
table never invalidates it).

The one exception: `order` and `revenue_recognition_entry` gain a new
NOT NULL `asset_id` column, and this is dev/test data with no production
rows to preserve, so those two tables are truncated first rather than
threading a backfill through a temporary nullable column.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0c29e674c81a'
down_revision = '2d3ac137aa03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- table renames (data preserved) -----------------------------------
    op.rename_table('customer', 'account')
    op.rename_table('customer_type', 'account_type')
    op.rename_table('customer_assignment', 'account_assignment')

    # --- column renames (customer_id -> account_id), data preserved -------
    op.alter_column('contact', 'customer_id', new_column_name='account_id')
    op.alter_column('account_assignment', 'customer_id', new_column_name='account_id')
    op.alter_column('opportunity', 'customer_id', new_column_name='account_id')
    op.alter_column('agreement', 'customer_id', new_column_name='account_id')
    op.alter_column('project', 'customer_id', new_column_name='account_id')
    op.alter_column('communication', 'customer_id', new_column_name='account_id')
    op.alter_column('notification', 'customer_id', new_column_name='account_id')
    op.alter_column('order', 'customer_id', new_column_name='account_id')
    op.alter_column('revenue_recognition_entry', 'customer_id', new_column_name='account_id')
    op.alter_column('lead', 'converted_customer_id', new_column_name='converted_account_id')
    op.alter_column('account', 'customer_type_id', new_column_name='account_type_id')

    # --- new: Asset, the anchor for renewals (Salesforce's Asset object) --
    op.create_table('asset',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('account_id', sa.String(length=20), nullable=False),
        sa.Column('agreement_id', sa.String(length=40), nullable=False),
        sa.Column('campaign_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('renewed_by_opportunity_id', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.Column('updated_by', sa.String(length=64), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.id']),
        sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id']),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id']),
        sa.ForeignKeyConstraint(['renewed_by_opportunity_id'], ['opportunity.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agreement_id'),
    )

    # order/revenue_recognition_entry are getting a NOT NULL asset_id column;
    # this is disposable dev/test data (both tables were introduced by the
    # immediately-preceding migration), so truncate rather than backfill.
    op.execute('TRUNCATE TABLE revenue_recognition_entry, "order" RESTART IDENTITY CASCADE')

    op.add_column('order', sa.Column('asset_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('fk_order_asset_id', 'order', 'asset', ['asset_id'], ['id'])

    op.add_column('revenue_recognition_entry', sa.Column('asset_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('fk_revenue_recognition_entry_asset_id', 'revenue_recognition_entry', 'asset',
                          ['asset_id'], ['id'])

    # opportunity.originating_asset_id — the other half of the renewal loop,
    # nullable (most opportunities aren't a renewal of anything).
    op.add_column('opportunity', sa.Column('originating_asset_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_opportunity_originating_asset_id', 'opportunity', 'asset',
                          ['originating_asset_id'], ['id'])


def downgrade() -> None:
    op.drop_constraint('fk_opportunity_originating_asset_id', 'opportunity', type_='foreignkey')
    op.drop_column('opportunity', 'originating_asset_id')

    op.drop_constraint('fk_revenue_recognition_entry_asset_id', 'revenue_recognition_entry', type_='foreignkey')
    op.drop_column('revenue_recognition_entry', 'asset_id')

    op.drop_constraint('fk_order_asset_id', 'order', type_='foreignkey')
    op.drop_column('order', 'asset_id')

    op.drop_table('asset')

    op.alter_column('account', 'account_type_id', new_column_name='customer_type_id')
    op.alter_column('lead', 'converted_account_id', new_column_name='converted_customer_id')
    op.alter_column('revenue_recognition_entry', 'account_id', new_column_name='customer_id')
    op.alter_column('order', 'account_id', new_column_name='customer_id')
    op.alter_column('notification', 'account_id', new_column_name='customer_id')
    op.alter_column('communication', 'account_id', new_column_name='customer_id')
    op.alter_column('project', 'account_id', new_column_name='customer_id')
    op.alter_column('agreement', 'account_id', new_column_name='customer_id')
    op.alter_column('opportunity', 'account_id', new_column_name='customer_id')
    op.alter_column('account_assignment', 'account_id', new_column_name='customer_id')
    op.alter_column('contact', 'account_id', new_column_name='customer_id')

    op.rename_table('account_assignment', 'customer_assignment')
    op.rename_table('account_type', 'customer_type')
    op.rename_table('account', 'customer')
