"""add pulse signals and lead signal_points

Revision ID: fb2e5174c29e
Revises: 4281f80e8018
Create Date: 2026-09-01 11:09:57.641880
"""
from alembic import op
import sqlalchemy as sa


revision = 'fb2e5174c29e'
down_revision = '4281f80e8018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('strength', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('practice_hint', sa.String(length=60), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'type', 'source', name='uq_signal_identity')
    )
    op.add_column('lead', sa.Column('signal_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'signal_points')
    op.drop_table('signal')
    # ### end Alembic commands ###
