"""add communication provider_message_id

Revision ID: 0042b27d4b06
Revises: b8e4f1c96a2d
Create Date: 2026-09-21 00:00:00.000000

Hand-written, not autogenerated: the only schema change here is one plain
nullable column add, which autogenerate handles correctly on its own (see
fa86cf5ee990's identical shape for opened_at/replied_at) — writing it by
hand just skips the round trip of generating, inspecting, and re-saving an
autogenerate diff that would come out identical to this.

The SMS channel value itself needs no migration: Communication.channel is a
plain String(30) column (see models/activity_models.py), not a Postgres
enum type — the channel vocabulary (models.enums.LeadCommunicationChannel)
is a Python-level allow-list enforced in activity_service.py, so adding SMS
to it is a code change only.
"""
from alembic import op
import sqlalchemy as sa


revision = '0042b27d4b06'
down_revision = 'b8e4f1c96a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('communication', sa.Column('provider_message_id', sa.String(length=64), nullable=True))


def downgrade() -> None:
    op.drop_column('communication', 'provider_message_id')
