"""add lead linkedin url

Revision ID: 012928700d39
Revises: 9357bab24699
Create Date: 2026-08-24 09:47:30.117550
"""
from alembic import op
import sqlalchemy as sa


revision = '012928700d39'
down_revision = '9357bab24699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'linkedin_url')
    # ### end Alembic commands ###
