"""add lead whatsapp fields

Revision ID: 1a7f9c3d5e21
Revises: 0042b27d4b06
Create Date: 2026-09-21 00:00:00.000000

Hand-written, not autogenerated: five new nullable/defaulted columns on
lead (WhatsApp number, opt-in, opt-in source/timestamp, 24-hour window
expiry — see models/crm_models.py's Lead class for the field-by-field
rationale). Purely additive, does not touch any other lead migration.

WHATSAPP itself needs no migration to Communication.channel: same as SMS
(see 0042b27d4b06's docstring), it's a Python-level allow-list
(models.enums.LeadCommunicationChannel), not a Postgres enum type.
"""
from alembic import op
import sqlalchemy as sa


revision = '1a7f9c3d5e21'
down_revision = '0042b27d4b06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('lead', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    # Two-step nullable-then-drop-default pattern for the new NOT-NULL
    # boolean, same as 0e60621733d4's skip_weekends/auto_resolved: backfill
    # existing rows to the safe default (false) via server_default, then
    # drop it so future ORM inserts must supply the value explicitly.
    op.add_column('lead',
        sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('lead', 'whatsapp_opt_in', server_default=None)
    op.add_column('lead', sa.Column('whatsapp_opt_in_source', sa.String(length=50), nullable=True))
    op.add_column('lead', sa.Column('whatsapp_opt_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lead', sa.Column('whatsapp_window_expires_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('lead', 'whatsapp_window_expires_at')
    op.drop_column('lead', 'whatsapp_opt_in_at')
    op.drop_column('lead', 'whatsapp_opt_in_source')
    op.drop_column('lead', 'whatsapp_opt_in')
    op.drop_column('lead', 'whatsapp_number')
