"""add lead email and call insights

Revision ID: 8d53f1353ec0
Revises: d48740d826f1
Create Date: 2026-08-19 14:01:25.711990
"""
from alembic import op
import sqlalchemy as sa


revision = '8d53f1353ec0'
down_revision = 'd48740d826f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.add_column('communication', sa.Column('call_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('communication', sa.Column('call_outcome', sa.String(length=30), nullable=True))
    op.create_foreign_key('fk_communication_lead_id', 'communication', 'lead', ['lead_id'], ['id'])
    # ### end Alembic commands ###

    # autogenerate doesn't diff CheckConstraints — swap the old check for the new
    # one by hand. Its real DB name is still 'ck_communication_customer_or_agreement'
    # (a naming-drift leftover from the earlier Customer->Account rename, which
    # renamed the model's declared name but never the DB constraint itself) —
    # target that real name, not the current (already-drifted) model source name.
    op.drop_constraint('ck_communication_customer_or_agreement', 'communication', type_='check')
    op.create_check_constraint(
        'ck_communication_account_or_agreement_or_lead', 'communication',
        'account_id IS NOT NULL OR agreement_id IS NOT NULL OR lead_id IS NOT NULL',
    )


def downgrade() -> None:
    op.drop_constraint('ck_communication_account_or_agreement_or_lead', 'communication', type_='check')
    op.create_check_constraint(
        'ck_communication_customer_or_agreement', 'communication',
        'account_id IS NOT NULL OR agreement_id IS NOT NULL',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_communication_lead_id', 'communication', type_='foreignkey')
    op.drop_column('communication', 'call_outcome')
    op.drop_column('communication', 'call_duration_seconds')
    op.drop_column('communication', 'lead_id')
    # ### end Alembic commands ###
