"""add field permission

Revision ID: ba30464cb885
Revises: 90869f9eea5a
Create Date: 2026-08-27 12:34:07.963166
"""
from alembic import op
import sqlalchemy as sa


revision = 'ba30464cb885'
down_revision = '90869f9eea5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_permission_role_object_field', 'field_permission', ['role_id', 'object_name', 'field_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_permission_role_object_field', table_name='field_permission', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('field_permission')
    # ### end Alembic commands ###
