"""add employee password auth

Revision ID: d584fcd72357
Revises: 012928700d39
Create Date: 2026-08-24 11:17:42.229019
"""
from alembic import op
import sqlalchemy as sa


revision = 'd584fcd72357'
down_revision = '012928700d39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('employee', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # server_default backfills existing rows (no password yet -> must set one
    # before they can log in), then drop it — new rows always set this
    # explicitly via admin_service.create_employee(), same pattern as every
    # other NOT NULL column added to an existing table in this repo.
    op.add_column('employee', sa.Column('must_change_password', sa.Boolean(),
                                        nullable=False, server_default=sa.true()))
    op.alter_column('employee', 'must_change_password', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'must_change_password')
    op.drop_column('employee', 'password_hash')
    # ### end Alembic commands ###
