"""add lead web enrichment scoring

Revision ID: f45b8f6c3b76
Revises: fa86cf5ee990
Create Date: 2026-08-19 16:45:05.610418
"""
from alembic import op
import sqlalchemy as sa


revision = 'f45b8f6c3b76'
down_revision = 'fa86cf5ee990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('web_enrichment_points', sa.Integer(), nullable=True))
    op.add_column('lead', sa.Column('web_enrichment_summary', sa.String(length=2000), nullable=True))
    op.add_column('lead', sa.Column('web_enrichment_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead', 'web_enrichment_at')
    op.drop_column('lead', 'web_enrichment_summary')
    op.drop_column('lead', 'web_enrichment_points')
    # ### end Alembic commands ###
