"""add call dispositions and email open reply tracking

Revision ID: fa86cf5ee990
Revises: 8d53f1353ec0
Create Date: 2026-08-19 15:41:18.159458
"""
from alembic import op
import sqlalchemy as sa


revision = 'fa86cf5ee990'
down_revision = '8d53f1353ec0'
branch_labels = None
depends_on = None

call_disposition = sa.table(
    "call_disposition",
    sa.column("code", sa.String),
    sa.column("display_name", sa.String),
)

# The default, out-of-the-box set (mirrors models.enums.CallOutcome) — an
# admin can add/rename/retire further codes via /admin/lookups/call_disposition
# without a migration.
SEED = [
    {"code": "CONNECTED", "display_name": "Connected"},
    {"code": "VOICEMAIL", "display_name": "Voicemail"},
    {"code": "NO_ANSWER", "display_name": "No answer"},
    {"code": "BUSY", "display_name": "Busy"},
    {"code": "WRONG_NUMBER", "display_name": "Wrong number"},
    {"code": "OTHER", "display_name": "Other"},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_disposition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.bulk_insert(call_disposition, SEED)

    op.add_column('communication', sa.Column('call_disposition_id', sa.Integer(), nullable=True))
    op.add_column('communication', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('communication', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_communication_call_disposition_id', 'communication',
                          'call_disposition', ['call_disposition_id'], ['id'])
    # Dev-only data at this point (see prior migrations' truncation notes) —
    # a production rollout of this migration on populated data would need a
    # backfill mapping call_outcome's free text to call_disposition_id before
    # this drop; not needed here.
    op.drop_column('communication', 'call_outcome')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication', sa.Column('call_outcome', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint('fk_communication_call_disposition_id', 'communication', type_='foreignkey')
    op.drop_column('communication', 'replied_at')
    op.drop_column('communication', 'opened_at')
    op.drop_column('communication', 'call_disposition_id')
    op.drop_table('call_disposition')
    # ### end Alembic commands ###
